platform :ios, '7.0'

pod 'ECSlidingViewController', '~> 2.0.3'



pod 'RestKit', '~> 0.20.0'

# Testing and Search are optional components
pod 'RestKit/Testing', '~> 0.20.0'
pod 'RestKit/Search',  '~> 0.20.0'